### PR TITLE
Add additional participant properties, update substance use enums

### PR DESCRIPTION
**Pull request by mbkranz**
add current status property to participant yaml to identify the participants (ie clients) current status in the study protocol.

### CODE REVIEW

**Review by paulineribeyre — APPROVED** [review]

**Comment by mbkranz** [comment]
@paulineribeyre  Now that this is merged, does this live in an s3 bucket? If not can we deploy to an s3 bucket and I'll change the manifest accordingly?

**Comment by paulineribeyre** [comment]
@mbkranz it already leaves in an S3 bucket. See https://github.com/uc-cdis/cdis-manifest/blob/1531087/jcoin.datacommons.io/manifest.json#L37

**Comment by paulineribeyre** [comment]
Or do you mean, has it been released?

**Comment by paulineribeyre** [comment]
If so it's here: https://github.com/uc-cdis/JCOIN_datadictionary/releases/tag/1.3.0

**Comment by mbkranz** [comment]
Thats it thanks!

**Pull request merged**
