### PR TITLE
Paired back core measure focused data dictionary with updated descriptions and namings

### PR DESCRIPTION
**Pull request by mbkranz**
Paired back core measure focused data dictionary with updated descriptions and namings.

### Breaking Changes
Given name changes -- this will require corresponding changes to ETL mappings (eg follow up --> time_points; demographic --> demographic_baseline).

### Improvements
This version of the data dictionary more accurately reflects the JCOIN ccore measures and pairs back model to only include participant core measure sections. Additionally, descriptions were added and changed to better describe the core measure sections and contents of each node.  Added a few additional properties such as visit_dt.

Note, bash script was added to make renaming a little easier (ie follow_up references to time_point references)

### CODE REVIEW

**Comment by paulineribeyre** [comment]
> Given name changes -- this will require corresponding changes to ETL mappings (eg follow up --> time_points; demographic --> demographic_baseline).

@mbkranz is there existing data using the old names?

**Comment by mbkranz** [comment]
@paulineribeyre there is existing data with old names- although these data will be updated with new data (and new node names) I am working on.

 With that being said, one question I have: is the existing data's metadata (ie node names) not automatically updated when a data model node name is updated? It seems like there would/should be some sort of functionality for this right? I guess that is the main objective of other projects which bundle metadata and data such as PFBs....

**Comment by paulineribeyre** [comment]
@mbkranz there is no automation to update old data to new node names or property names. Once you deploy the new dictionary, the old data will still be in the DB, but it will not be reachable through the API anymore (including to delete it) since the API will not recognize the old names. So you could delete it while the old dictionary is deployed, then deploy the new dictionary, then submit the new data. Another strategy we use often for dictionaries is A/AB/B

**Comment by mbkranz** [comment]
@paulineribeyre  Ah makes sense. Ok - given there is no data in the QA env - could we do following:
1. deploy this new dictionary to QA, 
2. get one more round of review from team, 
3. Delete data from PROD when new DD is read for PROD (I like the A/AB/B approach but prob better off doing this approach as I've already deleted and changed nodes)

**Review by paulineribeyre — APPROVED** [review]

**Pull request merged**
